### Spam Email Filtering

In [ ]:
# Bài tập 1: 
# - Từ data e1-->e10 tạo lại file train_data.txt/.csv
# - Đọc file
# - Tạo ma trận thưa
# - Train - Test
# - Dự báo Test
# - Đánh giá độ chính xác

# Bài tập 2:
# - Từ bộ data email spam (mLearning), rút gọn có 10-20 email, nwords = 100
# - Thực hiện bài toán MultinomialNB giống Bài tập 1


# Bài 1 

In [25]:
import numpy as np
from scipy.sparse import coo_matrix # for sparse matrix
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score # for evaluating results
path = 'Spam email data/' # data path
train_data_fn = 'train-features-10.txt'
test_data_fn = 'test-features.txt'
train_label_fn = 'train-labels-10.txt'
test_label_fn = 'test-labels.txt'

In [26]:
## read train label
train_label=[]
with open(train_label_fn) as f:
    content = f.readlines()
print('Content:',type(content),':\n', content)
# strip() function will remove all white space characters, tabs, new lines
for line in content:
    train_label.append(int(line.strip()))
print('Label:',type(content),':\n', train_label)


Content: <class 'list'> :
 ['0\n', '0\n', '1\n', '1\n', '1\n', '0\n', '1\n', '1\n', '0\n', '1']
Label: <class 'list'> :
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 1]


In [27]:
## read train data (2500 words)
data=[]
with open(train_data_fn) as f:
    content = f.readlines()
# print('Content:',type(content),':\n', content)
print('Content:', content[:5])

for line in content:
    data.append(line.strip())
print('Remove new line:', data[:5])

train_data = np.zeros((len(data), 3), dtype = int)
for i, line in enumerate(data):
    a = line.split(' ')
    train_data[i, :] = np.array([int(a[0]), int(a[1]), int(a[2])])
print('Train data: \n', train_data[:5])

Content: ['1 1 1\n', '1 4 1\n', '2 1 1 \n', '2 3 1\n', '3 1 1 \n']
Remove new line: ['1 1 1', '1 4 1', '2 1 1', '2 3 1', '3 1 1']
Train data: 
 [[1 1 1]
 [1 4 1]
 [2 1 1]
 [2 3 1]
 [3 1 1]]


In [40]:
def read_data(data_fn, label_fn):
    ## read label_fn
    with open( label_fn) as f:
        content = f.readlines()
    label = [int(x.strip()) for x in content]

    ## read data_fn
    with open( data_fn) as f:
        content = f.readlines()
    # remove '\n' at the end of each line
    content = [x.strip() for x in content] 

    dat = np.zeros((len(content), 3), dtype = int)
    
    for i, line in enumerate(content): 
        a = line.split(' ')
        dat[i, :] = np.array([int(a[0]), int(a[1]), int(a[2])])
    

    data = coo_matrix((dat[:, 2], (dat[:, 0] - 1, dat[:, 1] - 1)),\
             shape=(len(label), nwords))
    return (data, label)

In [34]:
# create a Sparse Matrix
nwords = 5 #vocabulary
nemails = len(train_label)

# coo_matrix((data, (i, j)), [shape=(M, N)])
row = train_data[:, 0] - 1 # index of file start 1
col = train_data[:, 1] - 1 # index of array start 0
data = train_data[:, 2]
coo_data = coo_matrix((data, (row, col)), shape=(nemails, nwords)).toarray()

for i in range(15):
    print('%5d'%row[i], end='')
print('\n')
for i in range(15):
    print('%5d'%col[i], end='')
print('\n')
for i in range(15):
    print('%5d'%data[i], end='')
print('\n')
# print (row[:15])
# print (col[:15])
# print (data[:15])
print('---------Feature vector:---------')
print(coo_data.shape)
print(coo_data[0][:100])


    0    0    1    1    2    2    2    3    3    3    3    4    4    5    5

    0    3    0    2    0    2    4    0    1    2    3    1    3    3    4

    1    1    1    1    1    1    1    1    1    1    1    1    1    1    1

---------Feature vector:---------
(10, 5)
[1 0 0 1 0]


In [42]:
(train_data, train_label)  = read_data(train_data_fn, train_label_fn)
(test_data, test_label)  = read_data(test_data_fn, test_label_fn)

MNB = MultinomialNB()
MNB.fit(coo_data, train_label)

y_pred = MNB.predict(test_data)
print('Training size = %d, accuracy = %.2f%%' % \
      (coo_data.shape[0], accuracy_score(test_label, y_pred)*100))

Training size = 10, accuracy = 54.55%


# Bài 2 

In [ ]:
import numpy as np
from scipy.sparse import coo_matrix # for sparse matrix
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score # for evaluating results
path = 'Spam email data/' # data path
train_data_fn = 'train-features-10.txt'
test_data_fn = 'test-features.txt'
train_label_fn = 'train-labels-10.txt'
test_label_fn = 'test-labels.txt'